[package]
name = "kvs"
version = "0.1.0"
authors = ["Jamrok <jamrok@users.noreply.github.com>"]
edition = "2021"
description = "A key-value store"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
derive_more = "0.99"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"